services:
  db:
    image: postgres:15
    container_name: courier_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    # ADD THIS BLOCK:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docs/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl:
    build: .
    container_name: courier_etl
    dns:
      - 127.0.0.11  # This is Docker's internal DNS (The Magic Link!)
      - 8.8.8.8     # This is Google (The Backup for the Internet)
    depends_on:
      db:
        condition: service_healthy # Now this has a rule to follow!
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400  # Smaller packets often pass through easier